logo: lc_logo.svg
logoAlt: Library Carpentry Logo
logoFooter: lc_logo.svg
logoFooterAlt: Library Carpentry Logo

git_repo: https://github.com/LibraryCarpentry/librarycarpentry.org

# Other websites
dc-website: https://datacarpentry.org/
swc-website:  https://software-carpentry.org/
carpentries-website: https://carpentries.org/

carpentries_workshops_page: https://carpentries.org/workshops/
carpentries_handbook: https://docs.carpentries.org 

footer_overview_text: Library Carpentry is a lesson program of The Carpentries.
